import Head from "next/head";
import Navbar from "./navbar/Navbar";

const Layout = ({ children, title = "LATAMonChain" }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="font-cascadia">
        <Navbar />
      </header>
      <main className="font-cascadia">{children}</main>
      <footer></footer>
    </>
  );
};

export default Layout;
